<template>
  <div class="media-sharing">
    <q-banner v-if="loadError" rounded class="bg-red-9 text-white q-mb-md">{{ loadError }}<template #action><q-btn flat color="white" label="Tentar novamente" @click="load" /></template></q-banner>
    <div v-if="loading" class="row justify-center q-pa-xl"><q-spinner color="primary" size="38px" /></div>
    <template v-else>
      <q-card class="tool"><q-card-section><div class="text-subtitle1 text-weight-bold">Avatar e assinatura</div><div class="text-caption text-grey-5">Arquivos pessoais disponíveis no seu perfil.</div></q-card-section><q-separator dark /><q-card-section class="row q-col-gutter-xl"><div v-for="media in mediaItems" :key="media.kind" class="col-12 col-md-6"><div class="text-weight-medium q-mb-sm">{{ media.label }}</div><div class="media-preview row items-center justify-center q-mb-md"><q-img v-if="media.url" :src="media.url" fit="contain" class="full-height full-width" /><q-icon v-else :name="media.icon" size="64px" color="grey-7" /></div><q-file v-model="media.file" dark dense outlined accept="image/jpeg,image/png" max-file-size="5242880" label="PNG ou JPEG, até 5 MB" @rejected="invalidFile"><template #prepend><q-icon name="upload_file" /></template></q-file><div class="row q-gutter-sm q-mt-sm"><q-btn flat dense color="primary" icon="upload" label="Enviar" no-caps :disable="!media.file" :loading="media.saving" @click="saveMedia(media)" /><q-btn flat dense color="negative" icon="delete" label="Excluir" no-caps :disable="!media.url" @click="deleteMedia(media)" /></div></div></q-card-section></q-card>

      <q-card class="tool q-mt-lg"><q-card-section class="row items-center justify-between"><div><div class="text-subtitle1 text-weight-bold">Compartilhamento do perfil</div><div class="text-caption text-grey-5">Crie links temporários e revogue o acesso quando quiser.</div></div><q-btn flat dense color="primary" icon="add_link" label="Novo link" no-caps @click="dialog=true" /></q-card-section><q-separator dark /><q-list v-if="links.length" dark separator><q-item v-for="link in links" :key="link.id || link.linkId"><q-item-section avatar><q-icon name="link" color="primary" /></q-item-section><q-item-section><q-item-label>{{ link.scope || 'Perfil' }}</q-item-label><q-item-label caption class="text-grey-5">Expira em {{ formatDate(link.expiresAtUtc) }} · {{ link.useCount || 0 }}/{{ link.maxUses || '∞' }} usos</q-item-label></q-item-section><q-item-section side class="row"><q-btn flat round dense color="primary" icon="open_in_new" aria-label="Abrir perfil público" @click="openPublic(link)" /><q-btn flat round dense color="negative" icon="link_off" aria-label="Revogar link" @click="revoke(link)" /></q-item-section></q-item></q-list><q-card-section v-else class="text-grey-5">Nenhum link de compartilhamento ativo.</q-card-section></q-card>
    </template>
    <q-dialog v-model="dialog"><q-card class="tool share-dialog"><q-card-section class="row items-center"><div class="text-h6">Novo link de compartilhamento</div><q-space /><q-btn flat round dense icon="close" v-close-popup /></q-card-section><q-card-section><label-form text-label="Escopo"><q-input v-model.trim="draft.scope" dark dense outlined :rules="requiredRules" placeholder="Profile" /></label-form><label-form text-label="Validade em horas"><q-input v-model.number="draft.expiresInHours" type="number" min="1" dark dense outlined :rules="positiveRules" /></label-form><label-form text-label="Máximo de acessos (opcional)"><q-input v-model.number="draft.maxUses" type="number" min="1" dark dense outlined /></label-form><div class="row justify-end q-mt-md"><q-btn flat color="primary" icon="link" label="Criar link" no-caps :loading="creating" @click="create" /></div></q-card-section></q-card></q-dialog>
  </div>
</template>
<script setup>
import { reactive, ref } from "vue";
import { useRouter } from "vue-router";
import LabelForm from "src/system/components/form/LabelForm.vue";
import useNotify from "src/composables/useNotify";
import { getApiErrorMessage } from "src/services/clientAuthService";
import { createShareLink, getAvatarUrl, getSignatureUrl, listShareLinks, removeAvatar, removeSignature, revokeShareLink, uploadAvatar, uploadSignature } from "src/services/clientMediaService";
const router = useRouter(), { successNotify, errorNotify } = useNotify(), loading = ref(true), loadError = ref(""), links = ref([]), dialog = ref(false), creating = ref(false), draft = reactive({ scope: "Profile", expiresInHours: 24, maxUses: null });
const mediaItems = reactive([{ kind: "avatar", label: "Avatar", icon: "person", file: null, url: "", saving: false }, { kind: "signature", label: "Assinatura", icon: "draw", file: null, url: "", saving: false }]);
const collection = (v) => Array.isArray(v) ? v : v?.items || v?.shareLinks || v?.data || [], urlOf = (v) => typeof v === "string" ? v : v?.url || v?.temporaryUrl || "";
const requiredRules = [(v) => Boolean(String(v || "").trim()) || "Campo obrigatório"], positiveRules = [(v) => Number(v) > 0 || "Informe um valor maior que zero"];
const load = async () => { loading.value = true; loadError.value = ""; const results = await Promise.allSettled([getAvatarUrl(), getSignatureUrl(), listShareLinks()]); mediaItems[0].url = results[0].status === "fulfilled" ? urlOf(results[0].value) : ""; mediaItems[1].url = results[1].status === "fulfilled" ? urlOf(results[1].value) : ""; if (results[2].status === "fulfilled") links.value = collection(results[2].value); if (results.every((r) => r.status === "rejected")) loadError.value = "Não foi possível carregar avatar, assinatura e compartilhamentos."; loading.value = false; };
const invalidFile = () => errorNotify("Use um arquivo PNG ou JPEG de até 5 MB.");
const saveMedia = async (media) => { media.saving = true; try { await (media.kind === "avatar" ? uploadAvatar : uploadSignature)(media.file); successNotify(`${media.label} enviado.`); media.file = null; await load(); } catch (e) { errorNotify(getApiErrorMessage(e, `Não foi possível enviar ${media.label.toLowerCase()}.`)); } finally { media.saving = false; } };
const deleteMedia = async (media) => { try { await (media.kind === "avatar" ? removeAvatar : removeSignature)(); successNotify(`${media.label} excluído.`); await load(); } catch (e) { errorNotify(getApiErrorMessage(e, `Não foi possível excluir ${media.label.toLowerCase()}.`)); } };
const create = async () => { creating.value = true; try { await createShareLink({ scope: draft.scope, expiresInHours: Number(draft.expiresInHours), maxUses: draft.maxUses ? Number(draft.maxUses) : null }); successNotify("Link criado."); dialog.value = false; await load(); } catch (e) { errorNotify(getApiErrorMessage(e, "Não foi possível criar o link.")); } finally { creating.value = false; } };
const revoke = async (link) => { try { await revokeShareLink(link.id || link.linkId); successNotify("Link revogado."); await load(); } catch (e) { errorNotify(getApiErrorMessage(e, "Não foi possível revogar o link.")); } };
const openPublic = (link) => { const token = link.token || link.shareToken; if (token) router.push(`/public/profile/${encodeURIComponent(token)}`); else errorNotify("O token deste link não está disponível."); };
const formatDate = (v) => v ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(v)) : "data não informada"; load();
</script>
<style scoped>.media-sharing{max-width:1180px;margin:0 auto}.media-preview{height:180px;border:1px dashed rgba(255,255,255,.25);border-radius:8px;overflow:hidden}.share-dialog{width:min(560px,calc(100vw - 32px))}</style>
