<template>
  <div class="account-security">
    <q-banner v-if="loadError" rounded class="bg-red-9 text-white q-mb-md">{{ loadError }}<template #action><q-btn flat color="white" label="Tentar novamente" @click="load" /></template></q-banner>
    <div v-if="loading" class="row justify-center q-pa-xl"><q-spinner color="primary" size="38px" /></div>
    <template v-else>
      <q-card class="tool"><q-card-section><div class="text-subtitle1 text-weight-bold">Onboarding</div><div class="text-caption text-grey-5">Etapa atual, pendências e próximas ações da sua conta.</div></q-card-section><q-separator dark /><q-card-section><q-badge outline color="primary" :label="onboardingLabel" /><q-list v-if="pendingActions.length" dark separator class="q-mt-md"><q-item v-for="action in pendingActions" :key="action.code || action"><q-item-section avatar><q-icon name="task_alt" color="warning" /></q-item-section><q-item-section>{{ actionLabel(action) }}</q-item-section></q-item></q-list><div v-else class="text-caption text-grey-5 q-mt-sm">Nenhuma pendência informada.</div></q-card-section></q-card>

      <q-card class="tool q-mt-lg"><q-card-section><div class="text-subtitle1 text-weight-bold">Confirmação de contatos</div><div class="text-caption text-grey-5">Solicite um código e confirme seu e-mail ou telefone.</div></q-card-section><q-separator dark /><q-card-section class="row q-col-gutter-lg"><q-form class="col-12 col-md-6" @submit.prevent="sendEmail"><label-form text-label="E-mail"><q-input v-model.trim="email.email" type="email" dark dense outlined :rules="emailRules" /></label-form><label-form text-label="Código recebido"><q-input v-model.trim="email.code" dark dense outlined autocomplete="one-time-code" /></label-form><div class="row q-gutter-sm"><q-btn type="submit" flat color="primary" label="Enviar código" no-caps :loading="email.sending" /><q-btn flat color="positive" label="Confirmar" no-caps :disable="!email.code" :loading="email.confirming" @click="validateEmail" /></div></q-form><q-form class="col-12 col-md-6" @submit.prevent="sendPhone"><label-form text-label="Telefone com código do país"><q-input v-model.trim="phone.number" dark dense outlined :rules="requiredRules" /></label-form><label-form text-label="Código recebido"><q-input v-model.trim="phone.code" dark dense outlined autocomplete="one-time-code" /></label-form><div class="row q-gutter-sm"><q-btn type="submit" flat color="primary" label="Enviar código" no-caps :loading="phone.sending" /><q-btn flat color="positive" label="Confirmar" no-caps :disable="!phone.code" :loading="phone.confirming" @click="validatePhone" /></div></q-form></q-card-section></q-card>

      <q-card class="tool q-mt-lg"><q-card-section><div class="text-subtitle1 text-weight-bold">Senha</div><div class="text-caption text-grey-5">Altere sua senha autenticada ou conclua uma recuperação por código.</div></q-card-section><q-separator dark /><q-card-section class="row q-col-gutter-lg"><q-form class="col-12 col-md-6" @submit.prevent="savePassword"><label-form text-label="Senha atual"><q-input v-model="password.current" type="password" dark dense outlined autocomplete="current-password" :rules="requiredRules" /></label-form><label-form text-label="Nova senha"><q-input v-model="password.next" type="password" dark dense outlined autocomplete="new-password" :rules="passwordRules" /></label-form><q-btn type="submit" flat color="primary" icon="password" label="Alterar senha" no-caps :loading="password.saving" /></q-form><q-form class="col-12 col-md-6" @submit.prevent="sendReset"><label-form text-label="E-mail para recuperação"><q-input v-model.trim="reset.email" type="email" dark dense outlined :rules="emailRules" /></label-form><label-form text-label="Código"><q-input v-model.trim="reset.code" dark dense outlined /></label-form><label-form text-label="Nova senha"><q-input v-model="reset.next" type="password" dark dense outlined :rules="passwordRules" /></label-form><label-form text-label="Confirmar nova senha"><q-input v-model="reset.confirm" type="password" dark dense outlined :rules="confirmRules" /></label-form><div class="row q-gutter-sm"><q-btn type="submit" flat color="primary" label="Solicitar código" no-caps :loading="reset.sending" /><q-btn flat color="positive" label="Redefinir" no-caps :disable="!reset.code" :loading="reset.completing" @click="finishReset" /></div></q-form></q-card-section></q-card>

      <q-card class="tool q-mt-lg"><q-card-section class="row items-center justify-between"><div><div class="text-subtitle1 text-weight-bold">Sessões</div><div class="text-caption text-grey-5">Dispositivos com acesso à sua conta.</div></div><q-btn flat dense color="negative" icon="logout" label="Revogar outras" no-caps :loading="revokingAll" @click="revokeOthers" /></q-card-section><q-separator dark /><q-list v-if="sessions.length" dark separator><q-item v-for="session in sessions" :key="session.id || session.sessionId"><q-item-section avatar><q-icon name="devices" color="primary" /></q-item-section><q-item-section><q-item-label>{{ session.deviceName || session.userAgent || 'Dispositivo' }}</q-item-label><q-item-label caption class="text-grey-5">{{ maskedIp(session.ipAddressMasked || session.ipAddress) }} · {{ formatDate(session.lastSeenAtUtc || session.createdAtUtc) }}</q-item-label></q-item-section><q-item-section side><q-badge v-if="session.isCurrent" color="positive">Atual</q-badge><q-btn v-else flat round dense color="negative" icon="logout" aria-label="Revogar sessão" @click="removeSession(session)" /></q-item-section></q-item></q-list><q-card-section v-else class="text-grey-5">Nenhuma sessão disponível.</q-card-section></q-card>
    </template>
  </div>
</template>

<script setup>
import { computed, reactive, ref } from "vue";
import LabelForm from "src/system/components/form/LabelForm.vue";
import useNotify from "src/composables/useNotify";
import { getApiErrorMessage } from "src/services/clientAuthService";
import { changeCurrentPassword, completePasswordReset, confirmEmail, confirmPhoneVerification, getOnboardingStatus, listSessions, requestEmailConfirmation, requestPasswordReset, requestPhoneVerification, revokeOtherSessions, revokeSession } from "src/services/clientAccountService";
const { successNotify, errorNotify } = useNotify();
const loading = ref(true), loadError = ref(""), onboarding = ref({}), sessions = ref([]), revokingAll = ref(false);
const email = reactive({ email: "", code: "", sending: false, confirming: false }), phone = reactive({ number: "", code: "", sending: false, confirming: false }), password = reactive({ current: "", next: "", saving: false }), reset = reactive({ email: "", code: "", next: "", confirm: "", sending: false, completing: false });
const collection = (value, keys = []) => Array.isArray(value) ? value : keys.map((key) => value?.[key]).find(Array.isArray) || value?.items || value?.data || [];
const pendingActions = computed(() => collection(onboarding.value, ["pendingActions", "requirements", "actions"]));
const onboardingLabel = computed(() => onboarding.value?.currentStep || onboarding.value?.status || onboarding.value?.stage || "Status não informado");
const requiredRules = [(value) => Boolean(String(value || "").trim()) || "Campo obrigatório"], emailRules = [...requiredRules, (value) => /^\S+@\S+\.\S+$/.test(value) || "E-mail inválido"], passwordRules = [...requiredRules, (value) => String(value).length >= 8 || "Use pelo menos 8 caracteres"], confirmRules = [...passwordRules, (value) => value === reset.next || "As senhas não conferem"];
const actionLabel = (action) => typeof action === "string" ? action : action.displayName || action.label || action.code || action.action;
const maskedIp = (value) => { if (!value) return "Local não informado"; if (value.includes("***")) return value; if (value.includes(".")) { const parts = value.split("."); return `${parts[0]}.${parts[1]}.***.***`; } return `${value.slice(0, 4)}:****:****`; };
const formatDate = (value) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "Data não informada";
const load = async () => { loading.value = true; loadError.value = ""; const results = await Promise.allSettled([getOnboardingStatus(), listSessions()]); if (results[0].status === "fulfilled") onboarding.value = results[0].value || {}; if (results[1].status === "fulfilled") sessions.value = collection(results[1].value, ["sessions"]); if (results.some((item) => item.status === "rejected")) loadError.value = "Não foi possível carregar todas as informações da conta."; loading.value = false; };
const run = async (state, key, action, success) => { state[key] = true; try { await action(); successNotify(success); await load(); } catch (error) { errorNotify(getApiErrorMessage(error, "Não foi possível concluir a ação.")); } finally { state[key] = false; } };
const sendEmail = () => run(email, "sending", () => requestEmailConfirmation(email.email), "Código de confirmação enviado.");
const validateEmail = () => run(email, "confirming", () => confirmEmail(email.email, email.code), "E-mail confirmado.");
const sendPhone = () => run(phone, "sending", () => requestPhoneVerification(phone.number), "Código de telefone enviado.");
const validatePhone = () => run(phone, "confirming", () => confirmPhoneVerification(phone.number, phone.code), "Telefone confirmado.");
const savePassword = () => run(password, "saving", () => changeCurrentPassword(password.current, password.next), "Senha alterada.");
const sendReset = () => run(reset, "sending", () => requestPasswordReset(reset.email), "Código de recuperação enviado.");
const finishReset = () => run(reset, "completing", () => completePasswordReset({ email: reset.email, code: reset.code, newPassword: reset.next, confirmNewPassword: reset.confirm }), "Senha redefinida.");
const removeSession = async (session) => { try { await revokeSession(session.id || session.sessionId); successNotify("Sessão revogada."); await load(); } catch (error) { errorNotify(getApiErrorMessage(error, "Não foi possível revogar a sessão.")); } };
const revokeOthers = async () => { revokingAll.value = true; try { await revokeOtherSessions(); successNotify("Outras sessões revogadas."); await load(); } catch (error) { errorNotify(getApiErrorMessage(error, "Não foi possível revogar as outras sessões.")); } finally { revokingAll.value = false; } };
load();
</script>
<style scoped>.account-security { max-width: 1180px; margin: 0 auto; }</style>
