<template>
  <div class="text-white"><q-form class="row justify-center" @submit.prevent="step === 'request' ? requestCode() : resetPassword()"><div class="col-md-3 col-10"><p class="text-muted-register">{{ step === 'request' ? 'Informe seu e-mail para receber o código de recuperação.' : 'Informe o código recebido e escolha uma nova senha.' }}</p><label-field labelInput="E-mail"><q-input v-model.trim="form.email" type="email" v-bind="{ ...$inputStyle }" :rules="emailRules" /></label-field><template v-if="step === 'complete'"><label-field labelInput="Código"><q-input v-model.trim="form.code" v-bind="{ ...$inputStyle }" :rules="requiredRules" autocomplete="one-time-code" /></label-field><label-field labelInput="Nova senha"><q-input v-model="form.password" type="password" v-bind="{ ...$inputStyle }" :rules="passwordRules" autocomplete="new-password" /></label-field><label-field labelInput="Confirmar nova senha"><q-input v-model="form.confirm" type="password" v-bind="{ ...$inputStyle }" :rules="confirmRules" autocomplete="new-password" /></label-field></template><div class="row q-gutter-md q-mt-lg"><q-btn outline class="col q-pa-md" label="Voltar" no-caps @click="back" /><q-btn type="submit" color="primary" class="col q-pa-md" :label="step === 'request' ? 'Enviar código' : 'Redefinir senha'" no-caps :loading="loading" /></div><q-btn v-if="step === 'complete'" flat color="primary" class="full-width q-mt-sm" label="Reenviar código" no-caps :disable="cooldown > 0" @click="requestCode">{{ cooldown ? ` (${cooldown}s)` : '' }}</q-btn></div></q-form></div>
</template>
<script setup>
import { onBeforeUnmount, reactive, ref } from "vue";
import LabelField from "src/system/components/form/LabelField.vue";
import useNotify from "src/composables/useNotify";
import { getApiErrorMessage } from "src/services/clientAuthService";
import { completePasswordReset, requestPasswordReset } from "src/services/clientAccountService";
const emit = defineEmits(["status-login"]), { successNotify, errorNotify } = useNotify(), step = ref("request"), loading = ref(false), cooldown = ref(0), form = reactive({ email: "", code: "", password: "", confirm: "" });
const requiredRules = [(v) => Boolean(String(v || "").trim()) || "Campo obrigatório"], emailRules = [...requiredRules, (v) => /^\S+@\S+\.\S+$/.test(v) || "E-mail inválido"], passwordRules = [...requiredRules, (v) => String(v).length >= 8 || "Use pelo menos 8 caracteres"], confirmRules = [...passwordRules, (v) => v === form.password || "As senhas não conferem"];
let timer; const startCooldown = () => { cooldown.value = 60; clearInterval(timer); timer = setInterval(() => { cooldown.value -= 1; if (cooldown.value <= 0) clearInterval(timer); }, 1000); };
const requestCode = async () => { loading.value = true; try { await requestPasswordReset(form.email); step.value = "complete"; startCooldown(); successNotify("Se a conta existir, o código será enviado."); } catch (e) { errorNotify(getApiErrorMessage(e, "Não foi possível solicitar a recuperação.")); } finally { loading.value = false; } };
const resetPassword = async () => { loading.value = true; try { await completePasswordReset({ email: form.email, code: form.code, newPassword: form.password, confirmNewPassword: form.confirm }); successNotify("Senha redefinida. Entre com a nova senha."); emit("status-login", "login"); } catch (e) { errorNotify(getApiErrorMessage(e, "Código inválido ou expirado.")); } finally { loading.value = false; } };
const back = () => step.value === "complete" ? step.value = "request" : emit("status-login", "login"); onBeforeUnmount(() => clearInterval(timer));
</script>
